### ISSUE TITLE
Is this compliant?

### ISSUE THREAD

**Issue by ivoba** [aggrosoft/oxid-cookie-compliance#5]
Hello, 
nice module but is it really compliant since on first hit cookies are all set?
Cookies are only removed when some categories are unchecked.

Shouldnt there be any cookie be set at all (maybe only technical necessary) in the first place?

**Comment by aggrosoft** [comment]
The module is compliant, but it is only able to block the default things that come with the flow theme e.g. Google analytics

If you add any third party things you will have to use the oxviewconfig functions added by the module to check if the cookie category was allowed. 

Technical cookies are never blocked, this is not needed by law.
